server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: fuhaiwei
  jpa:
    open-in-view: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
